# Generated by Django 4.0 on 2022-02-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_delete_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profilename',
            field=models.CharField(default='名無し', max_length=255),
        ),
    ]
