# Generated by Django 4.0 on 2022-02-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_profilename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilename',
            field=models.CharField(default='No Name', max_length=255),
        ),
    ]
