# Generated by Django 4.0 on 2022-02-05 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_profilename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profilename',
        ),
    ]
