# Generated by Django 4.0 on 2022-01-15 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_lists_shop_delete_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='lists',
        ),
        migrations.DeleteModel(
            name='Lists',
        ),
    ]
