# Generated by Django 4.0 on 2022-01-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.AddField(
            model_name='shop',
            name='avatar',
            field=models.ImageField(default='defo', upload_to='documents/'),
        ),
    ]
