# Generated by Django 4.0 on 2022-01-23 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_delete_document_shop_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avator', models.ImageField(upload_to='images/', verbose_name='avator')),
            ],
        ),
    ]
