# Generated by Django 4.0 on 2022-01-23 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='avatar',
        ),
        migrations.AddField(
            model_name='shop',
            name='avator',
            field=models.ImageField(default='images/default.png', upload_to='images/', verbose_name='avator'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avator',
            field=models.ImageField(default='images/default.png', upload_to='images/', verbose_name='avator'),
        ),
    ]
