# Generated by Django 4.0 on 2022-01-23 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('userapp', '0008_remove_shop_avatar_shop_avator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='avator',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
