# Generated by Django 4.0 on 2022-01-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_alter_userprofile_avator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avator',
            field=models.ImageField(default='default.jpg', upload_to='images/', verbose_name='avator'),
        ),
    ]
