# Generated by Django 4.0 on 2022-02-01 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0016_alter_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
