# Generated by Django 4.0 on 2022-02-01 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0017_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='username',
        ),
    ]
